### ISSUE TITLE
Multi-threaded render has race condition issues in release code

### ISSUE THREAD

**Issue by thobbsinteractive** [thobbsinteractive/magic-carpet-2-hd#228]
Unfortunately adding locking did not fix the issue and in Debug builds the threading works perfectly. What I am seeing is some lines not being drawn before the render moves on to the next Polygon.

**Comment by thobbs-mifcom** [comment]
Though my investigations at home I am seeing the Release code running multiple main render methods in parallel despite the fact I implemented even tighter locking controls last night that should force the wait in the main thread.
I believe this maybe happening because either because I have not use the static std::atomic for the thread count or more likely the compiler optimizations are running more of the code it thinks that it is okay to run in parallel. If static std::atomic does not work I can either: 
- Flag the main triangle render method in GameRenderHD to not be optimized (#pragma optimize( "", off )), this has the disadvantage of losing any optimization but it should behave like it does in Debug.
- I add the index of the polygon being drawn the tasks to ensure that it only waits for that specific triangle to be finished allowing the optimized threading to process other triangles at the same time. Note that this may lead to triangles being drawn out of order (hopefully not)

**Comment by thobbsinteractive** [comment]
Adding the keys for each thead was not the solution. Neither was pragma optimize( "", off ). 
 std::atomic was the solution. `std::atomic<bool> m_isTaskRunning;`
