### ISSUE TITLE
Away until the 10th of July

### ISSUE THREAD

**Issue by thobbsinteractive** [thobbsinteractive/magic-carpet-2-hd#96]
@GrimSqueaker @turican0 
Hi guys,

I will be in Majorca for a week which means I will not be about test pull requests. If anything truly urgent comes up that MUST be merged then I will look into giving one or both of you admin permissions on the Repo.

One other thing, to avoid us working on the same issues, please assign yourself to an issue (if you can) or add a comment and I will assign it too you.

Have a good weeks guys.

**Comment by GrimSqueaker** [comment]
Have a great time. :-)

**Comment by turican0** [comment]
Hey, thanks for the info.
Have a wonderful holiday.
I'm working on incorporating both renderers and need the code unchanged before I finish, so this is ideal.
I have code with both renderers now, but neither one is working now :( And before I send a pull request I want to fix everything. Once I get that done it won't be too much work. I'll compare both renderers again so that any bug fixes and renames will be reflected in both. I might put the viewport settings outside the renderers. Then I'll work on the Render refactor and prepare to add the virtual class and skeleton for the GL renderer from the opengl-game-render branch. And I'd also like to add a tester that renders a frame with one renderer, then switches to the other, saves the screenshot, renders the screen with the other renderer, and then compares the two.
I'll see what I can do, but as I wrote, not moving the code for a while is now ideal for me. When the request gets approved is irrelevant in that case. It just makes sense to create anything bigger after my update is incorporated.

I hope to have everything done by the time you get back.

**Comment by thobbsinteractive** [comment]
Cool. I already have a skeleton for the OpenGL render if you want me to commit it into the pull request?

**Comment by turican0** [comment]
Hi, not in the main branch, but if you have it in the opengl-game-render branch, I'll take the code from there. Alternatively, post if you have newer code somewhere.

P.S.: Hooray I already found the bug that was causing the problem in the old renderer, just fix the new one and I can continue the renderers chapter!!!

**Comment by thobbsinteractive** [comment]
I put it into:
https://github.com/thobbsinteractive/magic-carpet-2-hd/tree/render-refactor
That is the branch with the pull request open
